#!/bin/bash

USER=mazelord
ScreenName=tunnel2by
KeyFile=/home/misc/misc/hack/key/id_dsa.smslib
DestIP=162.105.79.9
DestPort=2222
RemoteUser=libmgr

## Tunnel
BindAddr=127.0.0.1
ListenPort=3127
TUNNEL="-D $BindAddr:$ListenPort"

## Port Forwarding
LEET="-L 3737:127.0.0.1:37 -L 3713:127.0.0.1:13"
TOR="-L 9050:127.0.0.1:9050"
VNC="-L 9507:127.0.0.1:9501"
SSH2gm="-L 3722:46610.info:22"
OpenVPN="-L 1194:127.0.0.1:1194"
PortF="$SSH2gm $OpenVPN"

if [[ $UID -ne 0 ]]; then
  echo "become root to run this script."
  exit 1
fi

case "$1" in
	start|"")
		echo -n "Starting SSH Socks Tunnel: "
		if [[ `ls -R /var/run/screen/ | grep $ScreenName` ]]; then
			echo "$ScreenName already exists."
		else
			su $USER -c "screen -dmS $ScreenName ssh $RemoteUser@$DestIP -p $DestPort -i $KeyFile $TUNNEL $PortF -N"
			echo "$ScreenName."
		fi
		;;
	stop)
		echo -n "Stopping SSH Socks Tunnel: "
		if [[ `ls -R /var/run/screen/ | grep $ScreenName` ]]; then
			ps aux | grep ssh | grep -v SCREEN | grep $ListenPort | awk '{ print $2 }' | xargs kill
			echo "$ScreenName."
		else
			echo "$ScreenName not running."
		fi
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 3
		;;
esac
exit 0
